package persistance;
// Generated 15 oct. 2016 16:32:47 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Hotel generated by hbm2java
 */
public class Hotel implements java.io.Serializable {


    private int idhotel;
    private String adress;
    private String nom;
    private Integer nbrEtoile;
    private Set reservations = new HashSet(0);

    public Hotel() {
    }


    public Hotel(int idhotel) {
        this.idhotel = idhotel;
    }

    public Hotel(int idhotel, String adress, String nom, Integer nbrEtoile, Set reservations) {
        this.idhotel = idhotel;
        this.adress = adress;
        this.nom = nom;
        this.nbrEtoile = nbrEtoile;
        this.reservations = reservations;
    }

    public int getIdhotel() {
        return this.idhotel;
    }

    public void setIdhotel(int idhotel) {
        this.idhotel = idhotel;
    }

    public String getAdress() {
        return this.adress;
    }

    public void setAdress(String adress) {
        this.adress = adress;
    }

    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public Integer getNbrEtoile() {
        return this.nbrEtoile;
    }

    public void setNbrEtoile(Integer nbrEtoile) {
        this.nbrEtoile = nbrEtoile;
    }

    public Set getReservations() {
        return this.reservations;
    }

    public void setReservations(Set reservations) {
        this.reservations = reservations;
    }


}


