package persistance;
// Generated 15 oct. 2016 16:32:47 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private int idreservation;
     private Client client;
     private Hotel hotel;
     private Date dateReservation;
     private String nbrNuit;
     private String typePenssion;

    public Reservation() {
    }

	
    public Reservation(int idreservation) {
        this.idreservation = idreservation;
    }
    public Reservation(int idreservation, Client client, Hotel hotel, Date dateReservation, String nbrNuit, String typePenssion) {
       this.idreservation = idreservation;
       this.client = client;
       this.hotel = hotel;
       this.dateReservation = dateReservation;
       this.nbrNuit = nbrNuit;
       this.typePenssion = typePenssion;
    }
   
    public int getIdreservation() {
        return this.idreservation;
    }
    
    public void setIdreservation(int idreservation) {
        this.idreservation = idreservation;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }
    public Date getDateReservation() {
        return this.dateReservation;
    }
    
    public void setDateReservation(Date dateReservation) {
        this.dateReservation = dateReservation;
    }
    public String getNbrNuit() {
        return this.nbrNuit;
    }
    
    public void setNbrNuit(String nbrNuit) {
        this.nbrNuit = nbrNuit;
    }
    public String getTypePenssion() {
        return this.typePenssion;
    }
    
    public void setTypePenssion(String typePenssion) {
        this.typePenssion = typePenssion;
    }




}


